---
title: "Visualizing Geospatial Data in R"
author: "Mburu"
date: "2/18/2020"
output:
  github_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

```

## 

```{r}

library(ggmap)
library(tidyverse)
library(knitr)

corvallis <- c(lon = -123.2620, lat = 44.5646)
# 
# # Add a maptype argument to get a satellite map
readRenviron("~/.Renviron")
google_key <- Sys.getenv("GGMAP_GOOGLE_API_KEY")
register_google(google_key)

corvallis_map_sat <- get_map(corvallis, zoom = 13, maptype = "satellite")

```

## 


```{r}


sales <- readRDS("01_corv_sales.rds")
# Edit to display satellite map
ggmap(corvallis_map_sat) +
    geom_point(aes(lon, lat, color = year_built), data = sales)

```

```{r}



# Add source and maptype to get toner map from Stamen Maps
corvallis_map_bw <- get_map(corvallis, zoom = 13, 
                            maptype = "toner", source ="stamen")

# Edit to display toner map
ggmap(corvallis_map_bw) +
    geom_point(aes(lon, lat, color = year_built), data = sales)

```


```{r}
# Use base_layer argument to ggmap() to specify data and x, y mappings
ggmap(corvallis_map_bw,
      base_layer = ggplot(data = sales, aes(lon, lat )))+
    geom_point(aes(color = class))+ facet_wrap(~class)


```



```{r}
qmplot(lon, lat, data = sales, 
       geom = "point", color = bedrooms) +
    facet_wrap(~ month)

```


```{r}
ward_sales <- readRDS("01_corv_wards.rds")
head(ward_sales) %>% kable()
```

```{r}
ggplot(ward_sales, aes(lon, lat)) +
    geom_point(aes(color = ward))

```




```{r}
# Add a point layer with color mapped to group
ggplot(ward_sales, aes(lon, lat)) +
    geom_point(aes(color = group))


```


```{r}
ggplot(ward_sales, aes(lon, lat)) +
    geom_path(aes(group = group))


```


```{r}
# Add a polygon layer with fill mapped to ward, and group to group
ggplot(ward_sales, aes(lon, lat))+
    geom_polygon(aes(fill = ward, group = group))


```


```{r}
# Fix the polygon cropping
ggmap(corvallis_map_bw, extent = "normal", maprange = FALSE,
      base_layer = ggplot(ward_sales, aes(lon, lat))) +
    geom_polygon(aes(group = group, fill = ward))

```


```{r}
# Repeat, but map fill to num_sales
ggmap(corvallis_map_bw, 
      base_layer = ggplot(ward_sales, aes(lon, lat)),
      extent = "normal", maprange = FALSE) +
    geom_polygon(aes(group = group, fill = num_sales))

```



## 

```{r cars}
library(tidyverse)
library(sp)
library(sf)
```

## Including Plots

You can also embed plots, for example:

```{r}

countries_spdf <- readRDS("02_countries_spdf.rds")
summary(countries_spdf)
```


```{r}
# Call str() with max.level = 2 on countries_spdf
str(countries_spdf, max.level = 2)
```


```{r}
# Plot countries_spdf
plot(countries_spdf)
```



```{r}
one <- countries_spdf@polygons[[169]]

```


```{r}
# str() with max.level = 2, on the Polygons slot of one
str(one@Polygons, max.level = 2)

```


```{r}
str(one@Polygons[[6]], max.level = 2)
# Call plot on the coords slot of 6th element of one@Polygons

```


```{r}
# Call plot on the coords slot of 6th element of one@Polygons

plot(one@Polygons[[6]]@coords)

```


```{r}
one <- countries_spdf@polygons[[169]]

# str() with max.level = 2, on the Polygons slot of one
str(one@Polygons, max.level = 2)

```


```{r}
# str() with max.level = 2, on the 6th element of the one@Polygons

str(one@Polygons[[6]], max.level = 2)
# Call plot on the coords slot of 6th element of one@Polygons

```


```{r}

plot(one@Polygons[[6]]@coords)

```



```{r}
# Subset the 169th object of countries_spdf: usa
usa <- countries_spdf[169,]

# Look at summary() of usa

summary(usa)
```



```{r}
# Look at str() of usa

str(usa)


```


```{r}
# Call plot() on usa
plot(usa)
```


```{r}
# Call head() and str() on the data slot of countries_spdf

head(countries_spdf@data)

# Pull out the name column using $
```



```{r}
str(countries_spdf@data)
```


```{r}
countries_spdf$name
```


```{r}
# Pull out the subregion column using [[
countries_spdf[['subregion']]


```


```{r}
# Create logical vector: is_nz

is_nz <- countries_spdf$name == "New Zealand"
# Subset countries_spdf using is_nz: nz
nz <- countries_spdf[is_nz, ]

# Plot nz
plot(nz)

```


```{r}
library(tmap)

# Use qtm() to create a choropleth map of gdp

qtm(shp = countries_spdf, fill = "gdp")


```



```{r}
# Add style argument to the tm_fill() call
# Add a tm_borders() layer 
tm_shape(countries_spdf) +
  tm_fill(col = "population") +
  tm_borders(col = "burlywood4")

```


```{r}
# New plot, with tm_bubbles() instead of tm_fill()

tm_shape(countries_spdf) +
  tm_bubbles(size = "population") +
  tm_borders(col = "burlywood4")


```


```{r}
# Switch to a Hobo–Dyer projection
tm_shape(countries_spdf, projection = "hd") +
  tm_grid(n.x = 11, n.y = 11) +
  tm_fill(col = "population", style = "quantile")  +
  tm_borders(col = "burlywood4") 

```

